### ISSUE TITLE
Custom filename for lockfile

### ISSUE THREAD

**Issue by marcsauter** [marcsauter/single#1]

**Comment by leonklingele** [comment]
This has already been implemented, right?

https://github.com/marcsauter/single/blob/a99791ab4d950b7bd5bf5b1a4d23ed45b100aab1/single.go#L15

**Comment by fastfading** [comment]
for linux system  lock file locate at /var/lock
drwxrwxr-x.  5 root lock  4096 Apr  9 03:18 lock  
which only root or lock group can access
can we custom filename location ?
