### ISSUE TITLE
Return error instead of using log.Fatal

### ISSUE THREAD

**Issue by TheTechmage** [marcsauter/single#4]
Following the call stack, it appears that log.Fatal calls os.Exit. The documentation for os.Exit states that no defer calls will be run when exiting the application. This means that if someone wants to log to the syslog via `syslog.Warn("Failed to get lock")` or use some other logging mechanism, they can't.

**Comment by jrapoport** [comment]
https://github.com/marcsauter/single/pull/5

**Comment by leonklingele** [comment]
#5 has been merged :)
